language: php
php:
- 7.0
env:
script:
- sshpass -p $DEPLOY_PASS ssh -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "sh $DEPLOY_PATH/deploy.sh"
addons:
  apt:
    packages:
    - sshpass
sudo: false
branches:
  only:
  - master
